# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[34,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/Aesthetics/issues"
license="LGPL 3"
logoFile="aesthetics.png"

[[mods]]
modId="aesthetics"
version="${version}"
displayName="Simple Ores: Aesthetics"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/Aesthetics/1.16/update.json"
displayURL="http://minecraft.curseforge.com/projects/aesthetics"
credits="Created by AleXndrTheGr8st, maintained by Sinhika"
authors="AleXndrTheGr8st, Sinhika"
description='''An add-on for SimpleOres2 that adds decorative blocks such as bars, bricks, doors, stairs.
Also supports Netherrocks and Fusion metals.

Additional Credits: burunduk (Ukranian translation), Unknown (French)
'''

[[dependencies.aesthetics]] #optional
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aesthetics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.aesthetics]]
    modId="simpleores"
    mandatory=true
    versionRange="[1.16.3,]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.aesthetics]]
    modId="netherrocks"
    mandatory=false
    versionRange="[1.16.3,]"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.aesthetics]]
    modId="fusion"
    mandatory=false
    versionRange="[1.16.3,]"
    ordering="BEFORE"
    side="BOTH"
    
